//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string account_login {
            get {
                return ResourceManager.GetString("account_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập tài khoản.
        /// </summary>
        public static string account_loginaccount {
            get {
                return ResourceManager.GetString("account_loginaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string account_password {
            get {
                return ResourceManager.GetString("account_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string account_register {
            get {
                return ResourceManager.GetString("account_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản, nhấn đăng ký để tạo cho mình một tài khoản tại website.
        /// </summary>
        public static string account_registernote {
            get {
                return ResourceManager.GetString("account_registernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        public static string account_registertitle {
            get {
                return ResourceManager.GetString("account_registertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        public static string account_rememberme {
            get {
                return ResourceManager.GetString("account_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string account_username {
            get {
                return ResourceManager.GetString("account_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập vào đường dẫn này..
        /// </summary>
        public static string admin_accessdenied {
            get {
                return ResourceManager.GetString("admin_accessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép truy cập vào đường dẫn này HOẶC có lỗi trong quá trình xử lý dữ liệu. Hãy liên hệ với kỹ thuật viên nếu cần..
        /// </summary>
        public static string admin_accessdenied_des {
            get {
                return ResourceManager.GetString("admin_accessdenied_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn copy.
        /// </summary>
        public static string admin_ask_surecopy {
            get {
                return ResourceManager.GetString("admin_ask_surecopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa.
        /// </summary>
        public static string admin_ask_suredelete {
            get {
                return ResourceManager.GetString("admin_ask_suredelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính linh hoạt.
        /// </summary>
        public static string admin_attribute {
            get {
                return ResourceManager.GetString("admin_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thuộc tính cần hiển thị....
        /// </summary>
        public static string admin_attribute_chooseattribute {
            get {
                return ResourceManager.GetString("admin_attribute_chooseattribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string admin_cart_customer_name {
            get {
                return ResourceManager.GetString("admin_cart_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đặt.
        /// </summary>
        public static string admin_cart_datecreateorder {
            get {
                return ResourceManager.GetString("admin_cart_datecreateorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần xem cuối.
        /// </summary>
        public static string admin_cart_lastvieworder {
            get {
                return ResourceManager.GetString("admin_cart_lastvieworder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string admin_cart_order {
            get {
                return ResourceManager.GetString("admin_cart_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        public static string admin_cart_order_code {
            get {
                return ResourceManager.GetString("admin_cart_order_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết đơn hàng.
        /// </summary>
        public static string admin_cart_order_details {
            get {
                return ResourceManager.GetString("admin_cart_order_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string admin_cart_order_note {
            get {
                return ResourceManager.GetString("admin_cart_order_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục chỉnh sửa.
        /// </summary>
        public static string admin_cart_order_saveandedit {
            get {
                return ResourceManager.GetString("admin_cart_order_saveandedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và cập nhật thông tin sản phẩm.
        /// </summary>
        public static string admin_cart_order_saveandupdate {
            get {
                return ResourceManager.GetString("admin_cart_order_saveandupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng đơn hàng.
        /// </summary>
        public static string admin_cart_orderstatus {
            get {
                return ResourceManager.GetString("admin_cart_orderstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán hàng.
        /// </summary>
        public static string admin_cart_sales {
            get {
                return ResourceManager.GetString("admin_cart_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string admin_cart_status {
            get {
                return ResourceManager.GetString("admin_cart_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có thể chuyên mục cấp cha không thể nằm trong cấp con,hoặc 1 lỗi nào đó xãy ra. Có thể liên hệ vs kỹ thuật..
        /// </summary>
        public static string admin_cat_deletelevel {
            get {
                return ResourceManager.GetString("admin_cat_deletelevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục này không thể xóa vì nó có chứa các chuyên mục con..
        /// </summary>
        public static string admin_cat_deleteowner {
            get {
                return ResourceManager.GetString("admin_cat_deleteowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục đặc biệt.
        /// </summary>
        public static string admin_cat_feature {
            get {
                return ResourceManager.GetString("admin_cat_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string admin_common_accounts {
            get {
                return ResourceManager.GetString("admin_common_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc tính.
        /// </summary>
        public static string admin_common_attribute {
            get {
                return ResourceManager.GetString("admin_common_attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string admin_common_back {
            get {
                return ResourceManager.GetString("admin_common_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string admin_common_changepassword {
            get {
                return ResourceManager.GetString("admin_common_changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        public static string admin_common_cms {
            get {
                return ResourceManager.GetString("admin_common_cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string admin_common_code {
            get {
                return ResourceManager.GetString("admin_common_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh.
        /// </summary>
        public static string admin_common_config {
            get {
                return ResourceManager.GetString("admin_common_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string admin_common_confirm {
            get {
                return ResourceManager.GetString("admin_common_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string admin_common_content {
            get {
                return ResourceManager.GetString("admin_common_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string admin_common_create {
            get {
                return ResourceManager.GetString("admin_common_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chính.
        /// </summary>
        public static string admin_common_dashboard {
            get {
                return ResourceManager.GetString("admin_common_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã xóa sẽ không lấy lại được dữ liệu, hãy cân nhắc trước khi xóa. Bạn có thể nhấn nút quay lại nếu không muốn xóa nữa..
        /// </summary>
        public static string admin_common_deletedwarning {
            get {
                return ResourceManager.GetString("admin_common_deletedwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string admin_common_edit {
            get {
                return ResourceManager.GetString("admin_common_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string admin_common_hello {
            get {
                return ResourceManager.GetString("admin_common_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string admin_common_logout {
            get {
                return ResourceManager.GetString("admin_common_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string admin_common_name {
            get {
                return ResourceManager.GetString("admin_common_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string admin_common_page {
            get {
                return ResourceManager.GetString("admin_common_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại nội dung.
        /// </summary>
        public static string admin_common_posttype {
            get {
                return ResourceManager.GetString("admin_common_posttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string admin_common_product {
            get {
                return ResourceManager.GetString("admin_common_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công khai.
        /// </summary>
        public static string admin_common_public {
            get {
                return ResourceManager.GetString("admin_common_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhanh.
        /// </summary>
        public static string admin_common_quickcreate {
            get {
                return ResourceManager.GetString("admin_common_quickcreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string admin_common_save {
            get {
                return ResourceManager.GetString("admin_common_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string admin_common_stats {
            get {
                return ResourceManager.GetString("admin_common_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string admin_common_type {
            get {
                return ResourceManager.GetString("admin_common_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string admin_common_update {
            get {
                return ResourceManager.GetString("admin_common_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã được cập nhật.
        /// </summary>
        public static string admin_common_updated {
            get {
                return ResourceManager.GetString("admin_common_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        public static string admin_common_updatesuccessfully {
            get {
                return ResourceManager.GetString("admin_common_updatesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string admin_common_value {
            get {
                return ResourceManager.GetString("admin_common_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú ý!.
        /// </summary>
        public static string admin_common_warning {
            get {
                return ResourceManager.GetString("admin_common_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string admin_content_active {
            get {
                return ResourceManager.GetString("admin_content_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm ảnh.
        /// </summary>
        public static string admin_content_addpicture {
            get {
                return ResourceManager.GetString("admin_content_addpicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề nâng cao.
        /// </summary>
        public static string admin_content_advancetitle {
            get {
                return ResourceManager.GetString("admin_content_advancetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string admin_content_author {
            get {
                return ResourceManager.GetString("admin_content_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt File.
        /// </summary>
        public static string admin_content_browsefile {
            get {
                return ResourceManager.GetString("admin_content_browsefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt ảnh.
        /// </summary>
        public static string admin_content_browsepicture {
            get {
                return ResourceManager.GetString("admin_content_browsepicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ để biết giá.
        /// </summary>
        public static string admin_content_callforprice {
            get {
                return ResourceManager.GetString("admin_content_callforprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        public static string admin_content_category {
            get {
                return ResourceManager.GetString("admin_content_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chuyên mục....
        /// </summary>
        public static string admin_content_chooseyourcategory {
            get {
                return ResourceManager.GetString("admin_content_chooseyourcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string admin_content_content {
            get {
                return ResourceManager.GetString("admin_content_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string admin_content_createddate {
            get {
                return ResourceManager.GetString("admin_content_createddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string admin_content_delete {
            get {
                return ResourceManager.GetString("admin_content_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string admin_content_description {
            get {
                return ResourceManager.GetString("admin_content_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string admin_content_error {
            get {
                return ResourceManager.GetString("admin_content_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc biệt.
        /// </summary>
        public static string admin_content_feature {
            get {
                return ResourceManager.GetString("admin_content_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn thân thiện (SEO).
        /// </summary>
        public static string admin_content_friendlyurl {
            get {
                return ResourceManager.GetString("admin_content_friendlyurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        public static string admin_content_group {
            get {
                return ResourceManager.GetString("admin_content_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header HTML (Phải sử dụng HTML).
        /// </summary>
        public static string admin_content_headerhtml {
            get {
                return ResourceManager.GetString("admin_content_headerhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hình ảnh.
        /// </summary>
        public static string admin_content_imageslist {
            get {
                return ResourceManager.GetString("admin_content_imageslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string admin_content_info {
            get {
                return ResourceManager.GetString("admin_content_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string admin_content_keyword {
            get {
                return ResourceManager.GetString("admin_content_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string admin_content_language {
            get {
                return ResourceManager.GetString("admin_content_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa lần cuối.
        /// </summary>
        public static string admin_content_lastedit {
            get {
                return ResourceManager.GetString("admin_content_lastedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý chuyên mục.
        /// </summary>
        public static string admin_content_managecategory {
            get {
                return ResourceManager.GetString("admin_content_managecategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hình ảnh.
        /// </summary>
        public static string admin_content_manageimages {
            get {
                return ResourceManager.GetString("admin_content_manageimages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string admin_content_metadescription {
            get {
                return ResourceManager.GetString("admin_content_metadescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string admin_content_note {
            get {
                return ResourceManager.GetString("admin_content_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá cũ.
        /// </summary>
        public static string admin_content_oldprice {
            get {
                return ResourceManager.GetString("admin_content_oldprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string admin_content_order {
            get {
                return ResourceManager.GetString("admin_content_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cha.
        /// </summary>
        public static string admin_content_owner {
            get {
                return ResourceManager.GetString("admin_content_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string admin_content_picture {
            get {
                return ResourceManager.GetString("admin_content_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string admin_content_price {
            get {
                return ResourceManager.GetString("admin_content_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gốc.
        /// </summary>
        public static string admin_content_root {
            get {
                return ResourceManager.GetString("admin_content_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tạo thêm.
        /// </summary>
        public static string admin_content_saveandcreate {
            get {
                return ResourceManager.GetString("admin_content_saveandcreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục chỉnh sửa.
        /// </summary>
        public static string admin_content_saveandedit {
            get {
                return ResourceManager.GetString("admin_content_saveandedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và quản lý hình ảnh.
        /// </summary>
        public static string admin_content_saveandpicture {
            get {
                return ResourceManager.GetString("admin_content_saveandpicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string admin_content_title {
            get {
                return ResourceManager.GetString("admin_content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thứ tự.
        /// </summary>
        public static string admin_content_updateorder {
            get {
                return ResourceManager.GetString("admin_content_updateorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thứ tự thành công.
        /// </summary>
        public static string admin_content_updateordersuccessfully {
            get {
                return ResourceManager.GetString("admin_content_updateordersuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to với ngôn ngữ.
        /// </summary>
        public static string admin_content_withlang {
            get {
                return ResourceManager.GetString("admin_content_withlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận.
        /// </summary>
        public static string admin_email_datereceived {
            get {
                return ResourceManager.GetString("admin_email_datereceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string admin_email_phone {
            get {
                return ResourceManager.GetString("admin_email_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm theo tiêu đề.
        /// </summary>
        public static string admin_email_searchwithtitle {
            get {
                return ResourceManager.GetString("admin_email_searchwithtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        public static string admin_email_sender {
            get {
                return ResourceManager.GetString("admin_email_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người gửi.
        /// </summary>
        public static string admin_email_senderemail {
            get {
                return ResourceManager.GetString("admin_email_senderemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đăng ký bản tin.
        /// </summary>
        public static string admin_email_subscribe {
            get {
                return ResourceManager.GetString("admin_email_subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xem.
        /// </summary>
        public static string admin_email_viewed {
            get {
                return ResourceManager.GetString("admin_email_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ngôn ngữ đầy đủ.
        /// </summary>
        public static string admin_lang_code {
            get {
                return ResourceManager.GetString("admin_lang_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm đóng.
        /// </summary>
        public static string admin_lang_construction {
            get {
                return ResourceManager.GetString("admin_lang_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cờ.
        /// </summary>
        public static string admin_lang_flag {
            get {
                return ResourceManager.GetString("admin_lang_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngôn ngữ.
        /// </summary>
        public static string admin_lang_name {
            get {
                return ResourceManager.GetString("admin_lang_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ngôn ngữ rút gọn.
        /// </summary>
        public static string admin_lang_shortcode {
            get {
                return ResourceManager.GetString("admin_lang_shortcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string admin_menu_deactive {
            get {
                return ResourceManager.GetString("admin_menu_deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhằm tối ưu trong việc quản lý, chung tôi chỉ giới hạn hỗ trợ giá trị menu 3 cấp. Vui lòng kiểm tra lại việc thay đổi cấp độ giá trị menu..
        /// </summary>
        public static string admin_menu_deletelevel {
            get {
                return ResourceManager.GetString("admin_menu_deletelevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị menu này không thể xóa vì nó có chứa các giá trị con..
        /// </summary>
        public static string admin_menu_deleteowner {
            get {
                return ResourceManager.GetString("admin_menu_deleteowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ thuộc vào ngôn ngữ.
        /// </summary>
        public static string admin_menu_dependlang {
            get {
                return ResourceManager.GetString("admin_menu_dependlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string admin_menu_details {
            get {
                return ResourceManager.GetString("admin_menu_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu của mỗi ngôn ngữ sẽ độc lập với nhau.
        /// </summary>
        public static string admin_menu_eachlang {
            get {
                return ResourceManager.GetString("admin_menu_eachlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin menu.
        /// </summary>
        public static string admin_menu_infomation {
            get {
                return ResourceManager.GetString("admin_menu_infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn (Không kích hoạt).
        /// </summary>
        public static string admin_menu_invisible {
            get {
                return ResourceManager.GetString("admin_menu_invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị menu.
        /// </summary>
        public static string admin_menu_item {
            get {
                return ResourceManager.GetString("admin_menu_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chuyên mục.
        /// </summary>
        public static string admin_menu_itemcat {
            get {
                return ResourceManager.GetString("admin_menu_itemcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách giá trị menu.
        /// </summary>
        public static string admin_menu_itemlist {
            get {
                return ResourceManager.GetString("admin_menu_itemlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu cha.
        /// </summary>
        public static string admin_menu_itemowner {
            get {
                return ResourceManager.GetString("admin_menu_itemowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn trang.
        /// </summary>
        public static string admin_menu_itempage {
            get {
                return ResourceManager.GetString("admin_menu_itempage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại nội dung.
        /// </summary>
        public static string admin_menu_itemposttype {
            get {
                return ResourceManager.GetString("admin_menu_itemposttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu menu.
        /// </summary>
        public static string admin_menu_itemtype {
            get {
                return ResourceManager.GetString("admin_menu_itemtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách menu.
        /// </summary>
        public static string admin_menu_list {
            get {
                return ResourceManager.GetString("admin_menu_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên menu.
        /// </summary>
        public static string admin_menu_name {
            get {
                return ResourceManager.GetString("admin_menu_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string admin_menu_position {
            get {
                return ResourceManager.GetString("admin_menu_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nút chi tiết để quản lý các phần tử của mỗi menu.
        /// </summary>
        public static string admin_menu_pressdetails {
            get {
                return ResourceManager.GetString("admin_menu_pressdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy cập loại nội dung.
        /// </summary>
        public static string admin_posttype_access {
            get {
                return ResourceManager.GetString("admin_posttype_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào tên nhóm để bật/tắt tất cả các quyền..
        /// </summary>
        public static string admin_posttype_accessdescription {
            get {
                return ResourceManager.GetString("admin_posttype_accessdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy cập.
        /// </summary>
        public static string admin_posttype_accessrules {
            get {
                return ResourceManager.GetString("admin_posttype_accessrules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài Viết?.
        /// </summary>
        public static string admin_posttype_aspost {
            get {
                return ResourceManager.GetString("admin_posttype_aspost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị người tạo.
        /// </summary>
        public static string admin_posttype_authordisplay {
            get {
                return ResourceManager.GetString("admin_posttype_authordisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tính năng cơ bản.
        /// </summary>
        public static string admin_posttype_basicfeatures {
            get {
                return ResourceManager.GetString("admin_posttype_basicfeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chuyên mục.
        /// </summary>
        public static string admin_posttype_categorydescription {
            get {
                return ResourceManager.GetString("admin_posttype_categorydescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị chuyên mục.
        /// </summary>
        public static string admin_posttype_categorydisplay {
            get {
                return ResourceManager.GetString("admin_posttype_categorydisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        public static string admin_posttype_categoryfeature {
            get {
                return ResourceManager.GetString("admin_posttype_categoryfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chuyên mục.
        /// </summary>
        public static string admin_posttype_categoryimage {
            get {
                return ResourceManager.GetString("admin_posttype_categoryimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung chính (CKEditor).
        /// </summary>
        public static string admin_posttype_contentfeature {
            get {
                return ResourceManager.GetString("admin_posttype_contentfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string admin_posttype_create {
            get {
                return ResourceManager.GetString("admin_posttype_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string admin_posttype_createnewfeature {
            get {
                return ResourceManager.GetString("admin_posttype_createnewfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị ngày giờ tạo.
        /// </summary>
        public static string admin_posttype_datecreatedisplay {
            get {
                return ResourceManager.GetString("admin_posttype_datecreatedisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị ngày giờ sửa.
        /// </summary>
        public static string admin_posttype_dateeditdisplay {
            get {
                return ResourceManager.GetString("admin_posttype_dateeditdisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string admin_posttype_delete {
            get {
                return ResourceManager.GetString("admin_posttype_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tóm tắt.
        /// </summary>
        public static string admin_posttype_descriptionfeature {
            get {
                return ResourceManager.GetString("admin_posttype_descriptionfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string admin_posttype_display {
            get {
                return ResourceManager.GetString("admin_posttype_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string admin_posttype_edit {
            get {
                return ResourceManager.GetString("admin_posttype_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị người sửa.
        /// </summary>
        public static string admin_posttype_editordisplay {
            get {
                return ResourceManager.GetString("admin_posttype_editordisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hình ảnh(thêm hình không giới hạn).
        /// </summary>
        public static string admin_posttype_manageimagefeature {
            get {
                return ResourceManager.GetString("admin_posttype_manageimagefeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả cho các hình ảnh trong media.
        /// </summary>
        public static string admin_posttype_mediadescription {
            get {
                return ResourceManager.GetString("admin_posttype_mediadescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiên thị trên menu.
        /// </summary>
        public static string admin_posttype_menushow {
            get {
                return ResourceManager.GetString("admin_posttype_menushow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các thông sô Meta.
        /// </summary>
        public static string admin_posttype_metafeature {
            get {
                return ResourceManager.GetString("admin_posttype_metafeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính năng thêm.
        /// </summary>
        public static string admin_posttype_morefeatures {
            get {
                return ResourceManager.GetString("admin_posttype_morefeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân chia ngôn ngữ.
        /// </summary>
        public static string admin_posttype_multilanguage {
            get {
                return ResourceManager.GetString("admin_posttype_multilanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bật/Tắt.
        /// </summary>
        public static string admin_posttype_onofffeature {
            get {
                return ResourceManager.GetString("admin_posttype_onofffeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp thứ tự.
        /// </summary>
        public static string admin_posttype_orderfeature {
            get {
                return ResourceManager.GetString("admin_posttype_orderfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân cấp trang.
        /// </summary>
        public static string admin_posttype_pageownerfeature {
            get {
                return ResourceManager.GetString("admin_posttype_pageownerfeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ song song.
        /// </summary>
        public static string admin_posttype_parallellanguage {
            get {
                return ResourceManager.GetString("admin_posttype_parallellanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình đại diện.
        /// </summary>
        public static string admin_posttype_picturefeature {
            get {
                return ResourceManager.GetString("admin_posttype_picturefeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá cả.
        /// </summary>
        public static string admin_posttype_pricefeature {
            get {
                return ResourceManager.GetString("admin_posttype_pricefeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nút thêm nhanh.
        /// </summary>
        public static string admin_posttype_quickcreate {
            get {
                return ResourceManager.GetString("admin_posttype_quickcreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị loại bài viết trên seolink.
        /// </summary>
        public static string admin_posttype_showseolink {
            get {
                return ResourceManager.GetString("admin_posttype_showseolink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa Slug.
        /// </summary>
        public static string admin_posttype_slugedit {
            get {
                return ResourceManager.GetString("admin_posttype_slugedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê ở trang chính.
        /// </summary>
        public static string admin_posttype_statsatdashboard {
            get {
                return ResourceManager.GetString("admin_posttype_statsatdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị ảnh thu nhỏ.
        /// </summary>
        public static string admin_posttype_thumbnaildisplay {
            get {
                return ResourceManager.GetString("admin_posttype_thumbnaildisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề (nếu tắt tiêu đề sẽ tạo tự động).
        /// </summary>
        public static string admin_posttype_titlefeature {
            get {
                return ResourceManager.GetString("admin_posttype_titlefeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string admin_posttype_view {
            get {
                return ResourceManager.GetString("admin_posttype_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tùy chỉnh.
        /// </summary>
        public static string admin_px_configgroup {
            get {
                return ResourceManager.GetString("admin_px_configgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tùy chỉnh.
        /// </summary>
        public static string admin_px_pixeloption {
            get {
                return ResourceManager.GetString("admin_px_pixeloption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả các bài viết/nội dung thuộc loại nội dung này cũng sẽ bị xóa..
        /// </summary>
        public static string admin_status_allwillremove {
            get {
                return ResourceManager.GetString("admin_status_allwillremove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã copy thành công!.
        /// </summary>
        public static string admin_status_copiedsuccessfully {
            get {
                return ResourceManager.GetString("admin_status_copiedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã xóa thành công!.
        /// </summary>
        public static string admin_status_deletedsuccessfully {
            get {
                return ResourceManager.GetString("admin_status_deletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thành công!.
        /// </summary>
        public static string admin_status_successfully {
            get {
                return ResourceManager.GetString("admin_status_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string admin_user_account {
            get {
                return ResourceManager.GetString("admin_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm thành viên.
        /// </summary>
        public static string admin_user_role {
            get {
                return ResourceManager.GetString("admin_user_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string admin_user_username {
            get {
                return ResourceManager.GetString("admin_user_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string cart_cart {
            get {
                return ResourceManager.GetString("cart_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string cart_checkout {
            get {
                return ResourceManager.GetString("cart_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        public static string cart_continueshopping {
            get {
                return ResourceManager.GetString("cart_continueshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string cart_customer_address {
            get {
                return ResourceManager.GetString("cart_customer_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        public static string cart_customer_infomation {
            get {
                return ResourceManager.GetString("cart_customer_infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên khác hàng.
        /// </summary>
        public static string cart_customer_name {
            get {
                return ResourceManager.GetString("cart_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string cart_customer_phone {
            get {
                return ResourceManager.GetString("cart_customer_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string cart_delete {
            get {
                return ResourceManager.GetString("cart_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có sản phẩm nào trong giỏ hàng của bạn.
        /// </summary>
        public static string cart_noitem {
            get {
                return ResourceManager.GetString("cart_noitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string cart_order_note {
            get {
                return ResourceManager.GetString("cart_order_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string cart_productname {
            get {
                return ResourceManager.GetString("cart_productname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string cart_quantity {
            get {
                return ResourceManager.GetString("cart_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đơn hàng.
        /// </summary>
        public static string cart_sendorder {
            get {
                return ResourceManager.GetString("cart_sendorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string cart_total {
            get {
                return ResourceManager.GetString("cart_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        public static string cart_totalmoney {
            get {
                return ResourceManager.GetString("cart_totalmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string cart_unitprice {
            get {
                return ResourceManager.GetString("cart_unitprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng của bạn.
        /// </summary>
        public static string cart_yourcart {
            get {
                return ResourceManager.GetString("cart_yourcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất liệu.
        /// </summary>
        public static string ChatLieu {
            get {
                return ResourceManager.GetString("ChatLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang vừa xem.
        /// </summary>
        public static string common_backstep {
            get {
                return ResourceManager.GetString("common_backstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang chủ.
        /// </summary>
        public static string common_backtohome {
            get {
                return ResourceManager.GetString("common_backtohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bởi.
        /// </summary>
        public static string common_by {
            get {
                return ResourceManager.GetString("common_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string common_category {
            get {
                return ResourceManager.GetString("common_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang bạn truy cập đang được xây dựng, vui lòng quay lại sau..
        /// </summary>
        public static string common_construction_description {
            get {
                return ResourceManager.GetString("common_construction_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string common_customer {
            get {
                return ResourceManager.GetString("common_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string common_date {
            get {
                return ResourceManager.GetString("common_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string common_description {
            get {
                return ResourceManager.GetString("common_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string common_home {
            get {
                return ResourceManager.GetString("common_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trong.
        /// </summary>
        public static string common_in {
            get {
                return ResourceManager.GetString("common_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền Email của bạn.
        /// </summary>
        public static string common_inputyouremail {
            get {
                return ResourceManager.GetString("common_inputyouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có hình ảnh nào.
        /// </summary>
        public static string common_nopic {
            get {
                return ResourceManager.GetString("common_nopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có nội dung nào.
        /// </summary>
        public static string common_nopost {
            get {
                return ResourceManager.GetString("common_nopost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trang.
        /// </summary>
        public static string common_page {
            get {
                return ResourceManager.GetString("common_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy trang.
        /// </summary>
        public static string common_pagenotfound {
            get {
                return ResourceManager.GetString("common_pagenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang mà bạn truy cập tạm thời bị gián đoạn, không tồn tại hoặc có lỗi trong việc xử lý. &lt;br&gt; Vui lòng quay lại sau. &lt;br&gt; Chúng tôi rất xin lỗi vì sự bất tiện. &lt;br&gt; (Nếu tình trạng này vẫn diễn ra xin vui lòng liên hệ với quản trị viên.).
        /// </summary>
        public static string common_pagenotfound_description {
            get {
                return ResourceManager.GetString("common_pagenotfound_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string common_readmore {
            get {
                return ResourceManager.GetString("common_readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string common_search {
            get {
                return ResourceManager.GetString("common_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa.
        /// </summary>
        public static string common_searchkeywordsinput {
            get {
                return ResourceManager.GetString("common_searchkeywordsinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nội dung phù hợp với từ khóa: .
        /// </summary>
        public static string common_searchnotfound {
            get {
                return ResourceManager.GetString("common_searchnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm với từ khóa: .
        /// </summary>
        public static string common_searchresultwithkeywords {
            get {
                return ResourceManager.GetString("common_searchresultwithkeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string common_send {
            get {
                return ResourceManager.GetString("common_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem trang.
        /// </summary>
        public static string common_viewingpage {
            get {
                return ResourceManager.GetString("common_viewingpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng đồng.
        /// </summary>
        public static string CongDong {
            get {
                return ResourceManager.GetString("CongDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string contact_address {
            get {
                return ResourceManager.GetString("contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string contact_email {
            get {
                return ResourceManager.GetString("contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string contact_form_address {
            get {
                return ResourceManager.GetString("contact_form_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền email của bạn.
        /// </summary>
        public static string contact_form_email {
            get {
                return ResourceManager.GetString("contact_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn của bạn chưa được gửi đi, vui lòng thử lại hoặc liên hệ với chúng tôi qua điện thoại (Xin lỗi vì sự bất tiện này)..
        /// </summary>
        public static string contact_form_fail {
            get {
                return ResourceManager.GetString("contact_form_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string contact_form_phone {
            get {
                return ResourceManager.GetString("contact_form_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string contact_form_subject {
            get {
                return ResourceManager.GetString("contact_form_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn của bạn đã được gửi đi thành công!.
        /// </summary>
        public static string contact_form_success {
            get {
                return ResourceManager.GetString("contact_form_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string contact_form_text {
            get {
                return ResourceManager.GetString("contact_form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền tên của bạn.
        /// </summary>
        public static string contact_form_yourname {
            get {
                return ResourceManager.GetString("contact_form_yourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string contact_info {
            get {
                return ResourceManager.GetString("contact_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string contact_location {
            get {
                return ResourceManager.GetString("contact_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string contact_phone {
            get {
                return ResourceManager.GetString("contact_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lien-he.
        /// </summary>
        public static string contact_slug {
            get {
                return ResourceManager.GetString("contact_slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH MỤC.
        /// </summary>
        public static string DanhMuc {
            get {
                return ResourceManager.GetString("DanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        public static string dichvu {
            get {
                return ResourceManager.GetString("dichvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string duan {
            get {
                return ResourceManager.GetString("duan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ trực tuyến.
        /// </summary>
        public static string HoTroTrucTuyen {
            get {
                return ResourceManager.GetString("HoTroTrucTuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string login_fail {
            get {
                return ResourceManager.GetString("login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string login_login {
            get {
                return ResourceManager.GetString("login_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ trạng thái đăng nhập?.
        /// </summary>
        public static string login_rememberme {
            get {
                return ResourceManager.GetString("login_rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUA NGAY.
        /// </summary>
        public static string MuaNgay {
            get {
                return ResourceManager.GetString("MuaNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận mail từ chúng tôi.
        /// </summary>
        public static string NhanMailTuChungToi {
            get {
                return ResourceManager.GetString("NhanMailTuChungToi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email của bạn.
        /// </summary>
        public static string NhapMailCuaBan {
            get {
                return ResourceManager.GetString("NhapMailCuaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        public static string project_showall {
            get {
                return ResourceManager.GetString("project_showall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Website.
        /// </summary>
        public static string project_visitwebsite {
            get {
                return ResourceManager.GetString("project_visitwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm liên quan.
        /// </summary>
        public static string SanPhamLienQuan {
            get {
                return ResourceManager.GetString("SanPhamLienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website thiết kế bởi SGP Media.
        /// </summary>
        public static string sgp_copyright {
            get {
                return ResourceManager.GetString("sgp_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website thiết kế bởi &lt;a href=&quot;http://saigonpixel.vn/vi/thiet-ke-website-chuyen-nghiep&quot;&gt;SGP Media&lt;/a&gt;.
        /// </summary>
        public static string sgp_copyright_withlink {
            get {
                return ResourceManager.GetString("sgp_copyright_withlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỊ TRƯỜNG.
        /// </summary>
        public static string ThiTruong {
            get {
                return ResourceManager.GetString("ThiTruong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê truy cập.
        /// </summary>
        public static string ThongKeTruyCap {
            get {
                return ResourceManager.GetString("ThongKeTruyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số kỹ thuật.
        /// </summary>
        public static string ThongSoKyThuat {
            get {
                return ResourceManager.GetString("ThongSoKyThuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string ThongTinLienHe {
            get {
                return ResourceManager.GetString("ThongTinLienHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string TinTuc {
            get {
                return ResourceManager.GetString("TinTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string web_photo {
            get {
                return ResourceManager.GetString("web_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh cửa hàng.
        /// </summary>
        public static string web_shopphotos {
            get {
                return ResourceManager.GetString("web_shopphotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bản đồ tại đây.
        /// </summary>
        public static string XemBanDoTaiDay {
            get {
                return ResourceManager.GetString("XemBanDoTaiDay", resourceCulture);
            }
        }
    }
}
