//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> Post_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public Nullable<int> Quote_Id { get; set; }
        public Nullable<int> Product_Rate { get; set; }
        public bool Active { get; set; }
        public bool View { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
