//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public int ID { get; set; }
        public System.DateTime Ngay { get; set; }
        public int SoLuongTryCap { get; set; }
        public System.DateTime LanTruyCapGanNhat { get; set; }
    }
}
