//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Role_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual Product Product { get; set; }
    }
}
