//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupVariant
    {
        public GroupVariant()
        {
            this.VariantAttributes = new HashSet<VariantAttribute>();
            this.OptionVariants = new HashSet<OptionVariant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public int Order { get; set; }
        public bool Active { get; set; }
        public bool Required { get; set; }
    
        public virtual ICollection<VariantAttribute> VariantAttributes { get; set; }
        public virtual ICollection<OptionVariant> OptionVariants { get; set; }
    }
}
