//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string country { get; set; }
    }
}
