//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Lang { get; set; }
        public Nullable<int> MenuPosition { get; set; }
        public bool Field_1_Enable { get; set; }
        public string Field_1_Label { get; set; }
        public bool Field_2_Enable { get; set; }
        public string Field_2_Label { get; set; }
        public bool Field_3_Enable { get; set; }
        public string Field_3_Label { get; set; }
    
        public virtual MenuPosition MenuPosition1 { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
