//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.PostType_Name = new HashSet<PostType_Name>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> Edit_Type { get; set; }
        public string Code { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Group { get; set; }
        public bool Public { get; set; }
    
        public virtual OptionGroup OptionGroup { get; set; }
        public virtual ICollection<PostType_Name> PostType_Name { get; set; }
    }
}
