//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionVariant
    {
        public OptionVariant()
        {
            this.Variants = new HashSet<Variant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public Nullable<int> GroupVariant_Id { get; set; }
        public Nullable<int> Variant_Id { get; set; }
        public string Color { get; set; }
    
        public virtual GroupVariant GroupVariant { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
    }
}
