//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public Order_Status()
        {
            this.Order_Item_Language = new HashSet<Order_Item_Language>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual ICollection<Order_Item_Language> Order_Item_Language { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
