//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item_Language
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lang { get; set; }
        public Nullable<int> Status_Id { get; set; }
    
        public virtual Order_Status Order_Status { get; set; }
    }
}
