//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string Attribute { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public string Product_Name { get; set; }
        public string SKU { get; set; }
        public string Image { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Post Post { get; set; }
    }
}
