//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAttribute
    {
        public PostAttribute()
        {
            this.AttributeValues = new HashSet<AttributeValue>();
            this.PostType_Name = new HashSet<PostType_Name>();
            this.Post_PostAttribute = new HashSet<Post_PostAttribute>();
            this.PostTypes = new HashSet<PostType>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Edit_Type { get; set; }
        public Nullable<int> Group { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual AttributeGroup AttributeGroup { get; set; }
        public virtual ICollection<AttributeValue> AttributeValues { get; set; }
        public virtual ICollection<PostType_Name> PostType_Name { get; set; }
        public virtual ICollection<Post_PostAttribute> Post_PostAttribute { get; set; }
        public virtual ICollection<PostType> PostTypes { get; set; }
    }
}
