//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_PostAttribute
    {
        public int Id_Post { get; set; }
        public int Id_Attribute { get; set; }
        public string Value { get; set; }
    
        public virtual PostAttribute PostAttribute { get; set; }
        public virtual Post Post { get; set; }
    }
}
