//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.MediaFiles = new HashSet<MediaFile>();
            this.MenuItems = new HashSet<MenuItem>();
            this.Order_Details = new HashSet<Order_Details>();
            this.Post1 = new HashSet<Post>();
            this.Post_PostAttribute = new HashSet<Post_PostAttribute>();
            this.Slugs = new HashSet<Slug>();
            this.VariantAttributes = new HashSet<VariantAttribute>();
            this.VariantAttributeCombinations = new HashSet<VariantAttributeCombination>();
            this.SpecialCats = new HashSet<SpecialCat>();
            this.PostTags = new HashSet<PostTag>();
            this.Cats = new HashSet<Cat>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Thumb { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Order { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_key { get; set; }
        public string Meta_Description { get; set; }
        public string Html_Head { get; set; }
        public Nullable<int> Owner_Id { get; set; }
        public Nullable<int> Level { get; set; }
        public string User_Create { get; set; }
        public string User_Edit { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
        public string Lang { get; set; }
        public Nullable<int> MainLang_Id { get; set; }
        public bool Active { get; set; }
        public string Code { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Price_Old { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public bool feature { get; set; }
        public bool onsale { get; set; }
        public bool Callforprice { get; set; }
        public bool newpost { get; set; }
        public bool ActiveProduct { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
    
        public virtual ICollection<MediaFile> MediaFiles { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual ICollection<Post> Post1 { get; set; }
        public virtual Post Post2 { get; set; }
        public virtual ICollection<Post_PostAttribute> Post_PostAttribute { get; set; }
        public virtual ICollection<Slug> Slugs { get; set; }
        public virtual PostType PostType { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<VariantAttribute> VariantAttributes { get; set; }
        public virtual ICollection<VariantAttributeCombination> VariantAttributeCombinations { get; set; }
        public virtual ICollection<SpecialCat> SpecialCats { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual ICollection<Cat> Cats { get; set; }
    }
}
