//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostType
    {
        public PostType()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.Posts = new HashSet<Post>();
            this.PostType_Name = new HashSet<PostType_Name>();
            this.Roles_PostType = new HashSet<Roles_PostType>();
            this.Slugs = new HashSet<Slug>();
            this.PostAttributes = new HashSet<PostAttribute>();
            this.Cats = new HashSet<Cat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Group { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Active { get; set; }
        public bool Menu { get; set; }
        public bool AsPost { get; set; }
        public bool ShowType { get; set; }
        public bool QuickCreate { get; set; }
        public bool DashboardStats { get; set; }
        public bool Has_Cat { get; set; }
        public bool Has_Description { get; set; }
        public bool Has_Thumb { get; set; }
        public bool Has_Content { get; set; }
        public bool Has_Price { get; set; }
        public bool Has_Owner { get; set; }
        public bool Has_Meta { get; set; }
        public bool Has_Media { get; set; }
        public bool Has_Create { get; set; }
        public bool Has_User_Create { get; set; }
        public bool Has_User_Edit { get; set; }
        public bool Has_Date_Create { get; set; }
        public bool Has_Date_Edit { get; set; }
        public bool Has_Order { get; set; }
        public bool Has_Lang { get; set; }
        public bool Has_Parallel_Language { get; set; }
        public bool Has_Title { get; set; }
        public bool Has_SpecialCat { get; set; }
        public bool Show_Thumb { get; set; }
        public bool Show_Cat { get; set; }
        public bool Show_Slug { get; set; }
        public bool Has_Active { get; set; }
        public string Icon { get; set; }
        public string Code { get; set; }
        public bool Has_feature { get; set; }
        public bool Has_onsale { get; set; }
        public bool Has_oldprice { get; set; }
        public bool Has_CatImage { get; set; }
        public bool Has_CatDescription { get; set; }
        public bool Has_Callforprice { get; set; }
        public bool Has_Catfeature { get; set; }
        public bool Has_MediaDescription { get; set; }
        public bool Has_CatBanner { get; set; }
        public bool Has_New { get; set; }
        public bool Active_Product { get; set; }
        public bool Active_Position { get; set; }
        public Nullable<int> Position { get; set; }
        public bool Tags { get; set; }
        public bool Field1 { get; set; }
        public bool Field2 { get; set; }
        public bool Field3 { get; set; }
        public bool Field4 { get; set; }
        public bool Field5 { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostType_Name> PostType_Name { get; set; }
        public virtual ICollection<Roles_PostType> Roles_PostType { get; set; }
        public virtual ICollection<Slug> Slugs { get; set; }
        public virtual ICollection<PostAttribute> PostAttributes { get; set; }
        public virtual ICollection<Cat> Cats { get; set; }
    }
}
