//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Discounts = new HashSet<Discount>();
            this.Inventories = new HashSet<Inventory>();
            this.Product_ProductAttribute = new HashSet<Product_ProductAttribute>();
            this.StockImports = new HashSet<StockImport>();
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string SKU { get; set; }
        public bool Inv_Active { get; set; }
        public int Inv_min_Quantity { get; set; }
        public bool Inv_OutStock { get; set; }
        public bool Inv_OutStockNoti { get; set; }
        public bool Inv_Backorder { get; set; }
        public string UpSell { get; set; }
        public string CrossSell { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
        public decimal Sale_Price { get; set; }
        public Nullable<System.DateTime> Sale_Start { get; set; }
        public Nullable<System.DateTime> Sale_End { get; set; }
        public decimal Weight { get; set; }
    
        public virtual ICollection<Discount> Discounts { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Product_ProductAttribute> Product_ProductAttribute { get; set; }
        public virtual ICollection<StockImport> StockImports { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
