//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Access
    {
        public int Role_Id { get; set; }
        public bool Admin { get; set; }
        public bool PixelAdmin { get; set; }
        public bool Option { get; set; }
        public bool Menu { get; set; }
        public bool User { get; set; }
        public bool Email { get; set; }
        public bool Header_Html { get; set; }
        public bool Order_View { get; set; }
        public bool Order_Control { get; set; }
        public bool Stats_View { get; set; }
        public bool Attribute { get; set; }
        public bool Inventory { get; set; }
        public bool Shipping { get; set; }
        public bool Files { get; set; }
        public bool History { get; set; }
        public bool field1 { get; set; }
        public bool field2 { get; set; }
        public bool field3 { get; set; }
    }
}
