//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slug
    {
        public int Id { get; set; }
        public Nullable<int> Post { get; set; }
        public Nullable<int> Cat { get; set; }
        public Nullable<int> PostType { get; set; }
        public string Slug1 { get; set; }
        public Nullable<int> Slug_Count { get; set; }
        public string Slug_Full { get; set; }
        public string Lang { get; set; }
    
        public virtual Post Post1 { get; set; }
        public virtual PostType PostType1 { get; set; }
        public virtual Cat Cat1 { get; set; }
    }
}
