//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTP
    {
        public SMTP()
        {
            this.EmailCampaigns = new HashSet<EmailCampaign>();
        }
    
        public int Id { get; set; }
        public string Port { get; set; }
        public string Server { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmailCampaign> EmailCampaigns { get; set; }
    }
}
