//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantAttribute
    {
        public VariantAttribute()
        {
            this.Variants = new HashSet<Variant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int VariantGroup_Id { get; set; }
        public Nullable<int> Type { get; set; }
        public int PostId { get; set; }
        public bool Active { get; set; }
    
        public virtual GroupVariant GroupVariant { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
        public virtual Post Post { get; set; }
    }
}
