//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal PriceOld { get; set; }
        public decimal Weight { get; set; }
        public int Order { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string SKU { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> VariantAtt_Id { get; set; }
        public int VariantOption_Id { get; set; }
        public bool Active { get; set; }
    
        public virtual VariantAttribute VariantAttribute { get; set; }
        public virtual OptionVariant OptionVariant { get; set; }
    }
}
