//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelCMS.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_Roles
    {
        public webpages_Roles()
        {
            this.Roles_PostType = new HashSet<Roles_PostType>();
            this.webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();
            this.EmailSubscribes = new HashSet<EmailSubscribe>();
            this.Discounts = new HashSet<Discount>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Roles_PostType> Roles_PostType { get; set; }
        public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual ICollection<EmailSubscribe> EmailSubscribes { get; set; }
        public virtual ICollection<Discount> Discounts { get; set; }
    }
}
